name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm' # <-- enables caching automatically

      - name: Block internet
        run: |
          sudo iptables -A OUTPUT -p tcp --dport 443 -j DROP
          sudo iptables -A OUTPUT -p tcp --dport 80 -j DROP

      
      - name: Install dependencies (verbose)
        run: npm install --verbose

      - name: List installed npm packages (full tree)
        run: npm ls --all

      - name: Show npm cache directory contents
        run: ls -R ~/.npm
